--<ScriptOptions statementTerminator=";"/>

CREATE TABLE admin (
	idadmin INT NOT NULL,
	ADMIN_ACCOUNT VARCHAR(45),
	ADMIN_PASSWORD INT,
	ADMIN_EMAIL TEXT,
	ADMIN_IC TEXT,
	ADMIN_NUMBER INT,
	PRIMARY KEY (idadmin)
) ENGINE=InnoDB;

CREATE TABLE adminevents (
	idadminevents INT NOT NULL,
	ADMIN_NUMBER VARCHAR(45),
	ADMIN_DATE VARCHAR(45),
	ADMIN_DETAILS VARCHAR(45),
	PRIMARY KEY (idadminevents)
) ENGINE=InnoDB;

CREATE TABLE basic (
	idbasic INT NOT NULL,
	BASIC_ACCOUNT VARCHAR(45),
	BASIC_PASSOWRD INT,
	BASIC_EMAIL TEXT,
	BASIC_IC TEXT,
	BASIC_NUMBER INT,
	BASIC_HISTORY TEXT,
	BASIC_BOOKING TEXT,
	PRIMARY KEY (idbasic)
) ENGINE=InnoDB;

CREATE TABLE gold (
	idgold INT NOT NULL,
	GOLD_ACCOUNT VARCHAR(45),
	GOLD_PASSWORD INT,
	GOLD_EMAIL TEXT,
	GOLD_IC TEXT,
	GOLD_NUMBER INT,
	GOLD_HISTORY TEXT,
	GOLD_BOOKING TEXT,
	PRIMARY KEY (idgold)
) ENGINE=InnoDB;

CREATE TABLE bronze (
	idbronze INT NOT NULL,
	BRONZE_ACCOUNT VARCHAR(45),
	BRONZE_PASSWORD INT,
	BRONZE_EMAIL TEXT,
	BRONZE_IC TEXT,
	BRONZE_NUMBER INT,
	BRONZE_HISTORY TEXT,
	BRONZE_BOOKING TEXT,
	PRIMARY KEY (idbronze)
) ENGINE=InnoDB;

CREATE TABLE users (
	Username VARCHAR(20) NOT NULL,
	Password VARCHAR(45) NOT NULL,
	telNo INT NOT NULL,
	firstName VARCHAR(45),
	lastName VARCHAR(45),
	creationDate VARCHAR(45),
	rank INT,
	email VARCHAR(45),
	pass_icNo VARCHAR(45),
	PRIMARY KEY (Username)
) ENGINE=InnoDB;

CREATE TABLE adminseats (
	idadminseats INT NOT NULL,
	ADMIN_ROWS INT,
	ADMIN_COLUMN INT,
	ADMIN_PRICE DECIMAL(10 , 0),
	ADMIN_AVAILBILITY INT,
	PRIMARY KEY (idadminseats)
) ENGINE=InnoDB;

CREATE TABLE silver (
	idsilver INT NOT NULL,
	SILVER_ACCOUNT VARCHAR(45),
	SILVER_PASSWORD INT,
	SILVER_EMAIL TEXT,
	SILVER_IC TEXT,
	SILVER_NUMBER INT,
	SILVER_HISTORY TEXT,
	SILVER_BOOKING TEXT,
	PRIMARY KEY (idsilver)
) ENGINE=InnoDB;

CREATE TABLE admintickets (
	idadmintickets INT NOT NULL,
	ADMIN_PRICE DECIMAL(10 , 0),
	ADMIN_NUMBER INT,
	ADMIN_LEFT INT,
	ADMIN_TOTAL INT,
	PRIMARY KEY (idadmintickets)
) ENGINE=InnoDB;

